version: '1'

services:
  nginx:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: paperless-ui
    ports:
      - "80:80"


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile_API
    container_name: springboot-api
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

    environment:
      - SPRING_PROFILES_ACTIVE=docker


  postgres:
    image: postgres:latest
    container_name: paperless-db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: 'paperless'
        POSTGRES_PASSWORD: 'paperless'
        POSTGRES_DB: 'paperless'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "paperless" ]
      interval: 10s
      timeout: 5s
      retries: 20


  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: 'rabbitmq'
    ports:
       - "5672:5672"
       - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq_user"
        RABBITMQ_DEFAULT_PASS: "rabbitmq_password"



  minio:
    image: minio/minio
    container_name: 'minio'
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: "minio_user"
      MINIO_SECRET_KEY: "minio_password"
    command: server /data --console-address ":9090"


  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
      - ELASTIC_PASSWORD=search_password
    ports:
      - 9200:9200
      - 9300:9300

    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/

