version: '3'

services:
  nginx:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: paperless-ui
    ports:
      - "80:80"


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile_API
    container_name: springboot-api
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_started
      rabbitmq:
        condition: service_started
      postgres:
        condition: service_healthy

    environment:
      - SPRING_PROFILES_ACTIVE=docker


  postgres:
    image: postgres:latest
    container_name: paperless-db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: 'paperless'
        POSTGRES_PASSWORD: 'paperless'
        POSTGRES_DB: 'paperless'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "paperless" ]
      interval: 10s
      timeout: 5s
      retries: 20


  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: 'rabbitmq'
    ports:
       - "5672:5672"
       - "9093:15672"
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq_user"
        RABBITMQ_DEFAULT_PASS: "rabbitmq_password"



  minio:
    image: minio/minio
    container_name: 'minio'
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: "minio_user"
      MINIO_SECRET_KEY: "minio_password"
    command: server /data --console-address ":9090"
